# Generated by Django 6.0.4 on 2026-07-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price_label', models.CharField(default='Cotizar', max_length=40)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Elemento del catálogo',
                'verbose_name_plural': 'Elementos del catálogo',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
