# Generated by Django 6.0.7 on 2026-07-22 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='ar_model',
            field=models.FileField(blank=True, null=True, upload_to='products/ar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb'])], verbose_name='Modelo de realidad aumentada'),
        ),
    ]
