# Generated by Django 6.0.7 on 2026-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='modelos_3d/'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
