# Generated by Django 6.0.7 on 2026-07-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_catalogitem_ar_model'),
        ('core', '0002_catalogitem_image_catalogitem_model_3d_and_more'),
    ]

    operations = [
    ]
