# Generated by Django 6.0.7 on 2026-07-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260722_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='category',
            field=models.CharField(choices=[('antivibratorios', 'Antivibratorios'), ('patas_niveladoras', 'Patas niveladoras'), ('accionamiento', 'Elementos de accionamiento y maniobra'), ('mobiliario', 'Niveladores para mobiliario')], max_length=80),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('colgantes', 'Colgantes antivibración'), ('niveladores_maq', 'Niveladores antivibración para maquinaria'), ('pies', 'Pies antivibración'), ('soportes_piso', 'Soportes antivibración con anclaje al piso'), ('tacones', 'Tacones antivibración'), ('alta_resistencia', 'Alta resistencia'), ('anclaje_piso', 'Anclaje al piso'), ('antiderrapante', 'Antiderrapante'), ('antivibracion', 'Antivibración'), ('con_rotula', 'Con rótula'), ('uso_rudo', 'Uso rudo')], max_length=80, null=True),
        ),
    ]
