# Generated by Django 6.0.7 on 2026-07-28 17:31

from django.db import migrations

import unicodedata

def normalize_key(value):
    text = unicodedata.normalize(
        "NFKD",
        value or "",
    )

    text = "".join(
        character
        for character in text
        if not unicodedata.combining(character)
    )

    text = (
        text.lower()
        .replace("_", " ")
        .replace("-", " ")
    )

    return " ".join(text.split())


RAW_VALUE_MAP = {
    # Categorías principales.
    "antivibratorios": (
        "antivibratorios",
        "",
    ),
    "antivibratorio": (
        "antivibratorios",
        "",
    ),
    "patas niveladoras": (
        "patas_niveladoras",
        "",
    ),
    "patas": (
        "patas_niveladoras",
        "",
    ),
    "elementos de accionamiento y maniobra": (
        "accionamiento",
        "",
    ),
    "accionamiento": (
        "accionamiento",
        "",
    ),
    "maniobra": (
        "accionamiento",
        "",
    ),
    "niveladores para mobiliario": (
        "mobiliario",
        "",
    ),
    "mobiliario": (
        "mobiliario",
        "",
    ),

    # Subcategorías de antivibratorios.
    "colgantes antivibracion": (
        "antivibratorios",
        "colgantes",
    ),
    "colgantes": (
        "antivibratorios",
        "colgantes",
    ),
    "niveladores antivibracion para maquinaria": (
        "antivibratorios",
        "niveladores_maq",
    ),
    "niveladores maq": (
        "antivibratorios",
        "niveladores_maq",
    ),
    "pies antivibracion": (
        "antivibratorios",
        "pies",
    ),
    "pies": (
        "antivibratorios",
        "pies",
    ),
    "soportes antivibracion con anclaje al piso": (
        "antivibratorios",
        "soportes_piso",
    ),
    "soportes piso": (
        "antivibratorios",
        "soportes_piso",
    ),
    "tacones antivibracion": (
        "antivibratorios",
        "tacones",
    ),
    "tacones": (
        "antivibratorios",
        "tacones",
    ),

    # Subcategorías de patas niveladoras.
    "alta resistencia": (
        "patas_niveladoras",
        "alta_resistencia",
    ),
    "anclaje al piso": (
        "patas_niveladoras",
        "anclaje_piso",
    ),
    "anclaje piso": (
        "patas_niveladoras",
        "anclaje_piso",
    ),
    "antiderrapante": (
        "patas_niveladoras",
        "antiderrapante",
    ),
    "antivibracion": (
        "patas_niveladoras",
        "antivibracion",
    ),
    "con rotula": (
        "patas_niveladoras",
        "con_rotula",
    ),
    "uso rudo": (
        "patas_niveladoras",
        "uso_rudo",
    ),
}


VALUE_MAP = {
    normalize_key(key): value
    for key, value in RAW_VALUE_MAP.items()
}


def normalize_catalog_values(
    apps,
    schema_editor,
):
    CatalogItem = apps.get_model(
        "core",
        "CatalogItem",
    )

    unknown_values = set()
    updated = 0

    for item in CatalogItem.objects.all().iterator():
        category_match = VALUE_MAP.get(
            normalize_key(item.category)
        )

        subcategory_match = VALUE_MAP.get(
            normalize_key(item.subcategory)
        )

        new_category = None
        new_subcategory = ""

        if category_match:
            new_category, new_subcategory = (
                category_match
            )

        if (
            subcategory_match
            and subcategory_match[1]
        ):
            new_category, new_subcategory = (
                subcategory_match
            )

        if not new_category:
            unknown_values.add(
                (
                    item.category or "",
                    item.subcategory or "",
                )
            )
            continue

        changed_fields = []

        if item.category != new_category:
            item.category = new_category
            changed_fields.append("category")

        if (
            (item.subcategory or "")
            != new_subcategory
        ):
            item.subcategory = new_subcategory
            changed_fields.append("subcategory")

        if changed_fields:
            item.save(
                update_fields=changed_fields
            )
            updated += 1

    print(
        f"Productos normalizados: {updated}"
    )

    if unknown_values:
        print(
            "Valores no reconocidos:"
        )

        for category, subcategory in sorted(
            unknown_values
        ):
            print(
                repr(category),
                repr(subcategory),
            )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_catalog_choices'),
    ]

    operations = [
    migrations.RunPython(
        normalize_catalog_values,
        migrations.RunPython.noop,
    ),
]
