# Generated by Django 5.2.17 on 2026-08-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_normalize_catalog_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntivibrationTechnicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(db_index=True, max_length=160, unique=True)),
                ('base_diameter', models.CharField(blank=True, max_length=255)),
                ('base_height', models.CharField(blank=True, max_length=255)),
                ('screw_diameter', models.CharField(blank=True, max_length=255)),
                ('screw_height', models.CharField(blank=True, max_length=255)),
                ('capacity_label', models.CharField(blank=True, max_length=120)),
                ('capacity_kg', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True)),
                ('elastomer_material', models.TextField(blank=True)),
                ('screw_material', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=255)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antivibration_data', to='core.catalogitem')),
            ],
        ),
        migrations.CreateModel(
            name='LevelerTechnicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(db_index=True, max_length=160, unique=True)),
                ('capacity_label', models.CharField(blank=True, max_length=120)),
                ('capacity_kg', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True)),
                ('type_label', models.CharField(blank=True, max_length=255)),
                ('metric_threads', models.TextField(blank=True)),
                ('standard_threads', models.TextField(blank=True)),
                ('base_diameter', models.CharField(blank=True, max_length=255)),
                ('screw_height', models.CharField(blank=True, max_length=255)),
                ('screw_material', models.TextField(blank=True)),
                ('base_material', models.TextField(blank=True)),
                ('product_url', models.URLField(blank=True, max_length=700)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=255)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leveler_data', to='core.catalogitem')),
            ],
        ),
    ]
